name: "Upgrade instance dependencies"
description: "Update the gem dependencies of a Decidim app"
author: "PokeCode"

inputs:
  ruby-version:
    description: "Ruby version to use"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ inputs.ruby-version }}

    - name: Install dependecies
      run: bundle install
      shell: bash

    - name: Update bundle dependencies
      run: |
        bundle update --patch --conservative
      shell: bash

    - name: "Execute decidim upgrade"
      run: |
        bin/rails decidim:upgrade
      shell: bash

    - name: Setup & create Database
      run: |
        bundle exec rails db:create db:schema:load
      shell: bash
      env:
        RAILS_ENV: development
        DATABASE_USERNAME: postgres
        DATABASE_PASSWORD: postgres

    - name: "Execute migrate"
      run: |
        bin/rails db:migrate
      shell: bash

    - name: Commit and create PR
      uses: peter-evans/create-pull-request@v7
      with:
        commit-message: "chore(deps): Update bundle dependencies"
        branch: "update-dependencies"
        title: "Update gem dependencies"
        body: |
          This PR updates gem dependencies using:
          ```
          bundle update --minor --conservative
          ```
